language: objective-c
osx_image: xcode10.1
xcode_workspace: YandexCheckoutPaymentsApi.xcworkspace
xcode_scheme: YCPaymentsApiExamplePods
cache:
  bundler: true
  cocoapods: true
  directories:
  - Carthage
notifications:
  slack:
    secure: X4KFw+xheuDW7t5mEQmD3UoV6+RqZoNfQpDCPWBVu0D7KZchZPDMyxVk2BW+q1kU59g3DMoXveN6WenDPBv/iec1pGJb6clBrrFuMZ5m5Ed/O3MdgmxGaOQBs0WTwe4APsOTlXLi0/KlPlfi6puArfGEhBMgzGk8HBCz9fz+FKwIgOFVrmYmuFezwSEeU2cA2UeFENjRRiBLETAs5f1SXeKdjqdDRisiN3x4TfB0gnY/SYumScVeftqWP/cYjJ5eV+ZUThejp0rgJ8/vnHFLRYSNKqRj8ZWX//buw5NX0rHTCEXccOy/G8Xw6YgaKaHg84b78TuUbHV3Tey4gNpUcyepMu3ShxbK4LAfAxDwx5K83wjtj2McQnntxXVxGM/ovTR6LPq7qZVlOle6ovIWVYpKdOvJvUa6hJxrLB+vnSuA0tX+9CqD+/h5FbBrDTnW7miS6BhtTEZel8B35sBPgUiOobM7ALc4xP6LrcInodntn69qo7eqouFUo67QvADqm2plf/TampKezcpTO1gQP0xhtbJyoLicCHOkTcwLvfu+norMAV6/sopvnZ255z0159DtEjr/PZD0Rdx76cevOoiQo8z03XIQu5MUECgO5Rb8vgcT77j6R7BAwOz5ICoQv23R0wppwpKDuvxOHJYTH9wGXILSB1LgGjIVmbzASrM=
before_install:
- brew update && brew bundle
- bundle install --jobs=3 --retry=3 --deployment
- pushd .
- bundle exec pod repo update
- bundle exec pod install
install: true
before_script:
- carthage bootstrap --platform iOS --cache-builds
script:
- swiftlint
- bundle exec fastlane build
- bundle exec fastlane scan
